---
resources:
- name: resource-sbalpi
  type: git
  source:
    uri: https://github.com/eivaskevicius/sbalpi.git

jobs:
- name: job-install-node-dependencies
  serial: true
  plan:
  - get: resource-sbalpi
    trigger: true
  - task: install dependencies
    file: resource-sbalpi/concourse/installDependencies.yml
- name: job-test-the-math
  plan:
  - task: test the math
    config:
      inputs:
      - name: resource-sbalpi
      - name: installed-node
    file: resource-sbalpi/concourse/testMath.yml