resources:
- name: resource-sbalpi-dev
  type: git
  source:
    uri: https://github.com/eivaskevicius/sbalpi.git
    branch: develop
- name: resource-sbalpi-snap
  type: git
  source:
    uri: https://github.com/eivaskevicius/sbalpi.git
    branch: snapshot
    private_key: ((publishing-private-key))

jobs:
- name: job-install-node-dependencies
  serial: true
  plan:
  - get: resource-sbalpi-dev
    trigger: true
  - task: install dependencies
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: latest
      inputs:
      - name: resource-sbalpi-dev
      caches:
      - path: resource-sbalpi-dev/node_modules
      outputs:
      - name: node_modules
      run:
        path: sh
        args: [resource-sbalpi-dev/src/scripts/nodeDependencies.sh]
  - task: test the math
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: latest
      inputs:
      - name: resource-sbalpi
      - name: node_modules
      caches:
      - path: resource-sbalpi-dev/node_modules
      run:
        path: sh
        args: [resource-sbalpi-dev/src/scripts/testMath.sh]
  - task: make a snapshot
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: resource-sbalpi
      - name: node_modules
      outputs:
      - name: snapshot
      run:
        path: sh
        args: [resource-sbalpi-dev/src/scripts/makeSnapshot.sh]
      - put: resource-sbalpi-snap
        params:
          repository: snapshot
        
