---
resources:
- name: resource-sbalpi
  type: git
  source:
    uri: https://github.com/eivaskevicius/sbalpi.git
# - name: resource-node
#   type: docker-image
#   source: { repository: node }

jobs:
- name: job-install-node-dependencies
  serial: true
  plan:
  - get: resource-sbalpi
  # - get: resource-node
  - task: install dependencies
    file: resource-sbalpi/concourse/install_dependencies.yml
  # - task: install npm dependencies
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: { repository: busybox }
  #     inputs:
  #       - name: resource-sbalpi
  #       - name: resource-node
      # run:
      #   path: resource-sbalpi/concourse/install_dependencies.yml
  
  # - task: test the math
  #   config:
  #     platform: linux
  #     image_resource: 
  #       type: docker-image
  #       source: { repository: node }
  #     inputs:
  #       - name: resourse-sbalpi
  #     run:
  #       path: resourse-sbalpi
  #       args: [npm test]